export  const events = [
    {
        id: 1,
        date: '22/2024',
        month: 'NOV',
        title: "Titre de l'événement ",
        venue: 'Venue 1',
        time: '00:00 AM - 00:00 PM',
        price: 499,
        interested: 10,
        image: 'https://www.welko.fr/wp-content/uploads/2022/11/open-angers_affiche-1024x724.jpg',
        description: "Lorem ipsum dolor sit amet consectetur. Eget vulputate sociis sit urna sit aliquet. Vivamus facilisis diam libero dolor volutpat diam eu. Quis a id posuere etiam at enim vivamus. Urna nisi malesuada libero enim ornare in viverra. Nibh commodo quis tellus aliquet nibh tristique lobortis id. Consequat ultricies vulputate turpis neque viverra tempor nunc. Et amet massa tellus consequat mauris imperdiet tellus. Praesent risus magna nisl turpis egestas ultrices viverra pellentesque blandit. Rutrum consequat eu penatibus ipsum at.",
    },
    {
        id: 2,
        date: '23/2024',
        month: 'DEC',
        title: "Autre événement",
        venue: 'Venue 2',
        time: '01:00 PM - 02:00 PM',
        price: 599,
        interested: 15,
        image: 'https://www.mairie-deuillabarre.fr/images/agenda/2023_/janvier-f%C3%A9vrier/Capture_d%C3%A9cran_2023-01-17_095301.jpg',
        description: "Lorem ipsum dolor sit amet consectetur. Eget vulputate sociis sit urna sit aliquet. Vivamus facilisis diam libero dolor volutpat diam eu. Quis a id posuere etiam at enim vivamus. Urna nisi malesuada libero enim ornare in viverra. Nibh commodo quis tellus aliquet nibh tristique lobortis id. Consequat ultricies vulputate turpis neque viverra tempor nunc. Et amet massa tellus consequat mauris imperdiet tellus. Praesent risus magna nisl turpis egestas ultrices viverra pellentesque blandit. Rutrum consequat eu penatibus ipsum at.",
    },
    {
        id: 3,
        date: '24/2024',
        month: 'JAN',
        title: "Titre de l'événement ",
        venue: 'Venue 1',
        time: '00:00 AM - 00:00 PM',
        price: 499,
        interested: 10,
        image: 'https://www.welko.fr/wp-content/uploads/2022/11/open-angers_affiche-1024x724.jpg',
        description: "Lorem ipsum dolor sit amet consectetur. Eget vulputate sociis sit urna sit aliquet. Vivamus facilisis diam libero dolor volutpat diam eu. Quis a id posuere etiam at enim vivamus. Urna nisi malesuada libero enim ornare in viverra. Nibh commodo quis tellus aliquet nibh tristique lobortis id. Consequat ultricies vulputate turpis neque viverra tempor nunc. Et amet massa tellus consequat mauris imperdiet tellus. Praesent risus magna nisl turpis egestas ultrices viverra pellentesque blandit. Rutrum consequat eu penatibus ipsum at.",
    },
    {
        id: 4,
        date: '24/2024',
        month: 'JAN',
        title: "Titre de l'événement ",
        venue: 'Venue 1',
        time: '00:00 AM - 00:00 PM',
        price: 499,
        interested: 10,
        image: 'https://www.welko.fr/wp-content/uploads/2022/11/open-angers_affiche-1024x724.jpg',
        description: "Lorem ipsum dolor sit amet consectetur. Eget vulputate sociis sit urna sit aliquet. Vivamus facilisis diam libero dolor volutpat diam eu. Quis a id posuere etiam at enim vivamus. Urna nisi malesuada libero enim ornare in viverra. Nibh commodo quis tellus aliquet nibh tristique lobortis id. Consequat ultricies vulputate turpis neque viverra tempor nunc. Et amet massa tellus consequat mauris imperdiet tellus. Praesent risus magna nisl turpis egestas ultrices viverra pellentesque blandit. Rutrum consequat eu penatibus ipsum at.",
    },
    {
        id: 5,
        date: '24/2024',
        month: 'JAN',
        title: "Titre de l'événement ",
        venue: 'Venue 1',
        time: '00:00 AM - 00:00 PM',
        price: 499,
        interested: 10,
        image: 'https://www.welko.fr/wp-content/uploads/2022/11/open-angers_affiche-1024x724.jpg',
        description: "Lorem ipsum dolor sit amet consectetur. Eget vulputate sociis sit urna sit aliquet. Vivamus facilisis diam libero dolor volutpat diam eu. Quis a id posuere etiam at enim vivamus. Urna nisi malesuada libero enim ornare in viverra. Nibh commodo quis tellus aliquet nibh tristique lobortis id. Consequat ultricies vulputate turpis neque viverra tempor nunc. Et amet massa tellus consequat mauris imperdiet tellus. Praesent risus magna nisl turpis egestas ultrices viverra pellentesque blandit. Rutrum consequat eu penatibus ipsum at.",
    },
    {
        id: 6,
        date: '24/2024',
        month: 'JAN',
        title: "Titre de l'événement ",
        venue: 'Venue 1',
        time: '00:00 AM - 00:00 PM',
        price: 499,
        interested: 10,
        image: 'https://www.welko.fr/wp-content/uploads/2022/11/open-angers_affiche-1024x724.jpg',
        description: "Lorem ipsum dolor sit amet consectetur. Eget vulputate sociis sit urna sit aliquet. Vivamus facilisis diam libero dolor volutpat diam eu. Quis a id posuere etiam at enim vivamus. Urna nisi malesuada libero enim ornare in viverra. Nibh commodo quis tellus aliquet nibh tristique lobortis id. Consequat ultricies vulputate turpis neque viverra tempor nunc. Et amet massa tellus consequat mauris imperdiet tellus. Praesent risus magna nisl turpis egestas ultrices viverra pellentesque blandit. Rutrum consequat eu penatibus ipsum at.",
    },
    {
        id: 7,
        date: '24/2024',
        month: 'JAN',
        title: "Titre de l'événement ",
        venue: 'Venue 1',
        time: '00:00 AM - 00:00 PM',
        price: 499,
        interested: 10,
        image: 'https://www.welko.fr/wp-content/uploads/2022/11/open-angers_affiche-1024x724.jpg',
        description: "Lorem ipsum dolor sit amet consectetur. Eget vulputate sociis sit urna sit aliquet. Vivamus facilisis diam libero dolor volutpat diam eu. Quis a id posuere etiam at enim vivamus. Urna nisi malesuada libero enim ornare in viverra. Nibh commodo quis tellus aliquet nibh tristique lobortis id. Consequat ultricies vulputate turpis neque viverra tempor nunc. Et amet massa tellus consequat mauris imperdiet tellus. Praesent risus magna nisl turpis egestas ultrices viverra pellentesque blandit. Rutrum consequat eu penatibus ipsum at.",
    },
    {
        id: 8,
        date: '24/2024',
        month: 'JAN',
        title: "Titre de l'événement ",
        venue: 'Venue 1',
        time: '00:00 AM - 00:00 PM',
        price: 499,
        interested: 10,
        image: 'https://www.welko.fr/wp-content/uploads/2022/11/open-angers_affiche-1024x724.jpg',
        description: "Lorem ipsum dolor sit amet consectetur. Eget vulputate sociis sit urna sit aliquet. Vivamus facilisis diam libero dolor volutpat diam eu. Quis a id posuere etiam at enim vivamus. Urna nisi malesuada libero enim ornare in viverra. Nibh commodo quis tellus aliquet nibh tristique lobortis id. Consequat ultricies vulputate turpis neque viverra tempor nunc. Et amet massa tellus consequat mauris imperdiet tellus. Praesent risus magna nisl turpis egestas ultrices viverra pellentesque blandit. Rutrum consequat eu penatibus ipsum at.",
    },
    {
        id: 9,
        date: '24/2024',
        month: 'JAN',
        title: "Titre de l'événement ",
        venue: 'Venue 1',
        time: '00:00 AM - 00:00 PM',
        price: 499,
        interested: 10,
        image: 'https://www.welko.fr/wp-content/uploads/2022/11/open-angers_affiche-1024x724.jpg',
        description: "Lorem ipsum dolor sit amet consectetur. Eget vulputate sociis sit urna sit aliquet. Vivamus facilisis diam libero dolor volutpat diam eu. Quis a id posuere etiam at enim vivamus. Urna nisi malesuada libero enim ornare in viverra. Nibh commodo quis tellus aliquet nibh tristique lobortis id. Consequat ultricies vulputate turpis neque viverra tempor nunc. Et amet massa tellus consequat mauris imperdiet tellus. Praesent risus magna nisl turpis egestas ultrices viverra pellentesque blandit. Rutrum consequat eu penatibus ipsum at.",
    },
];